name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.
version: 4.0.2

repository: https://github.com/grpc/grpc-dart

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.5.0
  crypto: ^3.0.0
  fixnum: ^1.0.0
  googleapis_auth: ^1.1.0
  meta: ^1.3.0
  http: '>=0.13.0 <2.0.0'
  http2: ^2.2.0
  protobuf: '>=2.0.0 <4.0.0'
  clock: ^1.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  lints: ^4.0.0
  mockito: ^5.0.0
  path: ^1.8.0
  test: ^1.16.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
  vm_service: ">=11.6.0 <15.0.0"
  fake_async: ^1.3.1

false_secrets:
 - interop/server1.key
 - test/data/localhost.key

topics:
 - grpc
 - rpc
 - protocols
