name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.
version: 3.2.4

repository: https://github.com/grpc/grpc-dart
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.10
  async: ^2.11.0
  crypto: ^3.0.3
  fixnum: ^1.1.0
  googleapis_auth: ^1.6.0
  meta: ^1.14.0
  http: '>=0.13.0 <2.0.0'
  http2: ^2.3.0
  protobuf: '>=2.0.0 <4.0.0'
  clock: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.9
  build_test: ^2.2.2
  lints: ">=2.0.0 <4.0.0"
  mockito: ^5.4.4
  path: ^1.9.0
  test: ^1.25.3
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  vm_service: ">=11.6.0 <15.0.0"
  fake_async: ^1.3.1

false_secrets:
 - interop/server1.key
 - test/data/localhost.key
