name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.

version: 3.0.0

repository: https://github.com/grpc/grpc-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  archive: ^3.0.0
  async: ^2.5.0
  crypto: ^3.0.0
  fixnum: ^1.0.0
  googleapis_auth: ^1.0.0
  meta: ^1.3.0
  http: ^0.13.0
  http2: ^2.0.0
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^1.3.4
  mockito: ^5.0.0-nullsafety.6
  path: ^1.8.0
  test: ^1.16.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
