name: grpc
description: Dart implementation of gRPC.
version: 0.4.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  googleapis_auth: ^0.2.3+6
  meta: ^1.0.5
  http: ^0.11.3+16
  http2: ^0.1.7

dev_dependencies:
  mockito: ^3.0.0-beta
  test: ^1.2.0
