name: grpc_web
description: Dart gRPC-Web sample client
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  grpc:
    path: ../../
  protobuf: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  lints: ^5.0.0
