name: grpc_web
description: Dart gRPC-Web sample client
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  grpc:
    path: ../../
  protobuf:

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: '^0.4.1'
