name: grpc_web
description: Dart gRPC-Web sample client
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc:
    path: ../../
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^2.0.0
