name: googleapis
description: Dart gRPC client sample for Google APIs
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.2.0
  fixnum:
  grpc:
    path: ../../
  protobuf: ">=3.0.0 <5.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.4
