name: googleapis
description: Dart gRPC client sample for Google APIs
version: 0.0.1
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async: ^1.13.3
  googleapis_auth: ^0.2.3+6
  grpc:
    path: ../../
  protobuf: ^0.6.0

dev_dependencies:
  test: ^0.12.0
