name: helloworld
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc:
    path: ../../
  protobuf: ^1.0.1
