name: interop
description: Dart gRPC interoperability test suite.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0
  async: ^2.2.0
  collection: ^1.14.11
  grpc:
    path: ../
  protobuf: ">=3.0.0 <5.0.0"

dev_dependencies:
  test: ^1.16.0
