name: metadata
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.2.0
  grpc:
    path: ../../
  protobuf: ">=3.0.0 <5.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.0
